# Site settings 配置站点
title: 'Jianzhu Guo'
description: 'Research & Coding'
keywords: ''
url: 'https://guojianzhu.com' # your host
# baseurl: /

# nav 中文字符空格：&emsp;
nav: # 最佳体验 六个标签 且最好每个标签不超过4中文字
  Homepage: '/'
  # Tags: '/tags.html'
  Timeline: '/timeline.html'
  About me: '/about.html'
  # Friend: '/friendLink.html'

# 博主
author: true
name: 'Jianzhu Guo'
NickName: 'cleardusk'
webtitle: 'Research & Coding'
bio: ''
about: true
aboutyou: '&emsp;&emsp;My name is Guo Jianzhu (郭建珠). I graduated from <a href="http://www.seu.edu.cn">Southeast University</a> with B.S. in GIS (Geographical Information System). Now, I am a Ph.D. student at <a href="http://www.nlpr.ia.ac.cn/nlpren/EN/volumn/home.shtml">National Laboratory of Pattern Recognition</a>, <a href="http://english.cas.cn">Chinese Academy of Sciences</a>, supervised by Prof. <a href="http://www.cbsr.ia.ac.cn/users/szli">Stan Z. Li</a>, where I mainly research on <b>face analysis</b>, <b>face recognition</b>, <b>3D face</b> and <b>deep learning</b>. <br/>&emsp;&emsp;More to see <a href="/2018/10/07/index.html">here</a>.'
portraits: 'assets/pics/me_v22.jpg' # your portraits image file path

# SNS
SNS: true
SNS-icon: #['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen']
  github: 'https://github.com/cleardusk'
  mail: 'mailto:jianzhu.guo@nlpr.ia.ac.cn'
  weixin: '/assets/pics/qrcode_me.jpg'
  

# 分页
paginate: 3
paginatepath: ['page:num']

# since
footer:
  since: 2018

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# 代码高亮 使用rouge
highlighter: rouge
# 代码高亮主题使用pygments主题: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 任选一个你喜欢的主题名称填在下面的单引号中
pygmentsTheme: 'default'

# 友情链接
# friends:
#   jekyll: 'https://www.jekyll.com.cn/'

# 评论 最佳体验 在disqus、livere和Gitment之间三选一
# disqus 评论
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# 来必力评论
livere: true
livere_uid: 'MTAyMC80MDE4Ny8xNjcxNA==' #'MTAyMC8zNDI2OS8xMDgwNg=='
# Gitment评论 OAuth Application
Gitment: false
Gitment_owner: ''  # github用户名
Gitment_repo: ''  # github博客存放的仓库名
client_id: ''  # 注册 OAuth Application 后获得的 client_id
client_secret: ''  # 注册 OAuth Application 后获得的 client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

# 百度统计 在baidu-url里填写自己相关的url代码
baidu: true
baidu-url: '88dcc3902c090f47dfc806d036168479'
# 谷歌分析 在google-ID里填写自己在谷歌分析获得的追踪ID
google: false
google-ID: ''

# 博客头信息备选颜色（该部分在站点中不充当站点变量，将其写在post的头信息中用来充当页面变量）
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
